/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as InviteInvitationIdIndexRouteImport } from './pages/invite/$invitationId/index'
import { Route as AppAccountIndexRouteImport } from './pages/_app/account/index'
import { Route as AppNoOrganizationSetOrganizationsRouteImport } from './pages/_app/_no-organization-set/organizations'
import { Route as AppOrganizationSetOrgOrgSlugLayoutRouteImport } from './pages/_app/_organization-set/org/$orgSlug/layout'
import { Route as AppOrganizationSetOrgOrgSlugIndexRouteImport } from './pages/_app/_organization-set/org/$orgSlug/index'
import { Route as AppOrganizationSetOrgOrgSlugTeamIndexRouteImport } from './pages/_app/_organization-set/org/$orgSlug/team/index'
import { Route as AppOrganizationSetOrgOrgSlugSettingsIndexRouteImport } from './pages/_app/_organization-set/org/$orgSlug/settings/index'
import { Route as AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRouteImport } from './pages/_app/_organization-set/org/$orgSlug/board/$boardId/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const InviteInvitationIdIndexRoute = InviteInvitationIdIndexRouteImport.update({
  id: '/invite/$invitationId/',
  path: '/invite/$invitationId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppNoOrganizationSetOrganizationsRoute =
  AppNoOrganizationSetOrganizationsRouteImport.update({
    id: '/_no-organization-set/organizations',
    path: '/organizations',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrganizationSetOrgOrgSlugLayoutRoute =
  AppOrganizationSetOrgOrgSlugLayoutRouteImport.update({
    id: '/_organization-set/org/$orgSlug',
    path: '/org/$orgSlug',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrganizationSetOrgOrgSlugIndexRoute =
  AppOrganizationSetOrgOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationSetOrgOrgSlugLayoutRoute,
  } as any)
const AppOrganizationSetOrgOrgSlugTeamIndexRoute =
  AppOrganizationSetOrgOrgSlugTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => AppOrganizationSetOrgOrgSlugLayoutRoute,
  } as any)
const AppOrganizationSetOrgOrgSlugSettingsIndexRoute =
  AppOrganizationSetOrgOrgSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrganizationSetOrgOrgSlugLayoutRoute,
  } as any)
const AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRoute =
  AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRouteImport.update({
    id: '/board/$boardId/',
    path: '/board/$boardId/',
    getParentRoute: () => AppOrganizationSetOrgOrgSlugLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/organizations': typeof AppNoOrganizationSetOrganizationsRoute
  '/account': typeof AppAccountIndexRoute
  '/invite/$invitationId': typeof InviteInvitationIdIndexRoute
  '/org/$orgSlug': typeof AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren
  '/org/$orgSlug/': typeof AppOrganizationSetOrgOrgSlugIndexRoute
  '/org/$orgSlug/settings': typeof AppOrganizationSetOrgOrgSlugSettingsIndexRoute
  '/org/$orgSlug/team': typeof AppOrganizationSetOrgOrgSlugTeamIndexRoute
  '/org/$orgSlug/board/$boardId': typeof AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/organizations': typeof AppNoOrganizationSetOrganizationsRoute
  '/account': typeof AppAccountIndexRoute
  '/invite/$invitationId': typeof InviteInvitationIdIndexRoute
  '/org/$orgSlug': typeof AppOrganizationSetOrgOrgSlugIndexRoute
  '/org/$orgSlug/settings': typeof AppOrganizationSetOrgOrgSlugSettingsIndexRoute
  '/org/$orgSlug/team': typeof AppOrganizationSetOrgOrgSlugTeamIndexRoute
  '/org/$orgSlug/board/$boardId': typeof AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_no-organization-set/organizations': typeof AppNoOrganizationSetOrganizationsRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/invite/$invitationId/': typeof InviteInvitationIdIndexRoute
  '/_app/_organization-set/org/$orgSlug': typeof AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren
  '/_app/_organization-set/org/$orgSlug/': typeof AppOrganizationSetOrgOrgSlugIndexRoute
  '/_app/_organization-set/org/$orgSlug/settings/': typeof AppOrganizationSetOrgOrgSlugSettingsIndexRoute
  '/_app/_organization-set/org/$orgSlug/team/': typeof AppOrganizationSetOrgOrgSlugTeamIndexRoute
  '/_app/_organization-set/org/$orgSlug/board/$boardId/': typeof AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/organizations'
    | '/account'
    | '/invite/$invitationId'
    | '/org/$orgSlug'
    | '/org/$orgSlug/'
    | '/org/$orgSlug/settings'
    | '/org/$orgSlug/team'
    | '/org/$orgSlug/board/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/organizations'
    | '/account'
    | '/invite/$invitationId'
    | '/org/$orgSlug'
    | '/org/$orgSlug/settings'
    | '/org/$orgSlug/team'
    | '/org/$orgSlug/board/$boardId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/_no-organization-set/organizations'
    | '/_app/account/'
    | '/invite/$invitationId/'
    | '/_app/_organization-set/org/$orgSlug'
    | '/_app/_organization-set/org/$orgSlug/'
    | '/_app/_organization-set/org/$orgSlug/settings/'
    | '/_app/_organization-set/org/$orgSlug/team/'
    | '/_app/_organization-set/org/$orgSlug/board/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  InviteInvitationIdIndexRoute: typeof InviteInvitationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/invite/$invitationId/': {
      id: '/invite/$invitationId/'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_no-organization-set/organizations': {
      id: '/_app/_no-organization-set/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppNoOrganizationSetOrganizationsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_organization-set/org/$orgSlug': {
      id: '/_app/_organization-set/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_organization-set/org/$orgSlug/': {
      id: '/_app/_organization-set/org/$orgSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof AppOrganizationSetOrgOrgSlugIndexRouteImport
      parentRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRoute
    }
    '/_app/_organization-set/org/$orgSlug/team/': {
      id: '/_app/_organization-set/org/$orgSlug/team/'
      path: '/team'
      fullPath: '/org/$orgSlug/team'
      preLoaderRoute: typeof AppOrganizationSetOrgOrgSlugTeamIndexRouteImport
      parentRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRoute
    }
    '/_app/_organization-set/org/$orgSlug/settings/': {
      id: '/_app/_organization-set/org/$orgSlug/settings/'
      path: '/settings'
      fullPath: '/org/$orgSlug/settings'
      preLoaderRoute: typeof AppOrganizationSetOrgOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRoute
    }
    '/_app/_organization-set/org/$orgSlug/board/$boardId/': {
      id: '/_app/_organization-set/org/$orgSlug/board/$boardId/'
      path: '/board/$boardId'
      fullPath: '/org/$orgSlug/board/$boardId'
      preLoaderRoute: typeof AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRouteImport
      parentRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRoute
    }
  }
}

interface AppOrganizationSetOrgOrgSlugLayoutRouteChildren {
  AppOrganizationSetOrgOrgSlugIndexRoute: typeof AppOrganizationSetOrgOrgSlugIndexRoute
  AppOrganizationSetOrgOrgSlugSettingsIndexRoute: typeof AppOrganizationSetOrgOrgSlugSettingsIndexRoute
  AppOrganizationSetOrgOrgSlugTeamIndexRoute: typeof AppOrganizationSetOrgOrgSlugTeamIndexRoute
  AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRoute: typeof AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRoute
}

const AppOrganizationSetOrgOrgSlugLayoutRouteChildren: AppOrganizationSetOrgOrgSlugLayoutRouteChildren =
  {
    AppOrganizationSetOrgOrgSlugIndexRoute:
      AppOrganizationSetOrgOrgSlugIndexRoute,
    AppOrganizationSetOrgOrgSlugSettingsIndexRoute:
      AppOrganizationSetOrgOrgSlugSettingsIndexRoute,
    AppOrganizationSetOrgOrgSlugTeamIndexRoute:
      AppOrganizationSetOrgOrgSlugTeamIndexRoute,
    AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRoute:
      AppOrganizationSetOrgOrgSlugBoardBoardIdIndexRoute,
  }

const AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren =
  AppOrganizationSetOrgOrgSlugLayoutRoute._addFileChildren(
    AppOrganizationSetOrgOrgSlugLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppNoOrganizationSetOrganizationsRoute: typeof AppNoOrganizationSetOrganizationsRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppOrganizationSetOrgOrgSlugLayoutRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppNoOrganizationSetOrganizationsRoute:
    AppNoOrganizationSetOrganizationsRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppOrganizationSetOrgOrgSlugLayoutRoute:
    AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  InviteInvitationIdIndexRoute: InviteInvitationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
