/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AppOrganizationSetIndexRouteImport } from './pages/_app/_organization-set/index'
import { Route as AppNoOrganizationSetOrganizationsRouteImport } from './pages/_app/_no-organization-set/organizations'
import { Route as AppOrganizationSetBoardBoardIdRouteImport } from './pages/_app/_organization-set/board/$boardId'
import { Route as AppOrganizationSetOrgOrgSlugLayoutRouteImport } from './pages/_app/_organization-set/org/$orgSlug/layout'
import { Route as AppOrganizationSetOrgOrgSlugIndexRouteImport } from './pages/_app/_organization-set/org/$orgSlug/index'
import { Route as AppOrganizationSetOrgOrgSlugTeamRouteImport } from './pages/_app/_organization-set/org/$orgSlug/team'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppOrganizationSetIndexRoute = AppOrganizationSetIndexRouteImport.update({
  id: '/_organization-set/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppNoOrganizationSetOrganizationsRoute =
  AppNoOrganizationSetOrganizationsRouteImport.update({
    id: '/_no-organization-set/organizations',
    path: '/organizations',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrganizationSetBoardBoardIdRoute =
  AppOrganizationSetBoardBoardIdRouteImport.update({
    id: '/_organization-set/board/$boardId',
    path: '/board/$boardId',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrganizationSetOrgOrgSlugLayoutRoute =
  AppOrganizationSetOrgOrgSlugLayoutRouteImport.update({
    id: '/_organization-set/org/$orgSlug',
    path: '/org/$orgSlug',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrganizationSetOrgOrgSlugIndexRoute =
  AppOrganizationSetOrgOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationSetOrgOrgSlugLayoutRoute,
  } as any)
const AppOrganizationSetOrgOrgSlugTeamRoute =
  AppOrganizationSetOrgOrgSlugTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AppOrganizationSetOrgOrgSlugLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/organizations': typeof AppNoOrganizationSetOrganizationsRoute
  '/': typeof AppOrganizationSetIndexRoute
  '/org/$orgSlug': typeof AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren
  '/board/$boardId': typeof AppOrganizationSetBoardBoardIdRoute
  '/org/$orgSlug/team': typeof AppOrganizationSetOrgOrgSlugTeamRoute
  '/org/$orgSlug/': typeof AppOrganizationSetOrgOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/organizations': typeof AppNoOrganizationSetOrganizationsRoute
  '/': typeof AppOrganizationSetIndexRoute
  '/board/$boardId': typeof AppOrganizationSetBoardBoardIdRoute
  '/org/$orgSlug/team': typeof AppOrganizationSetOrgOrgSlugTeamRoute
  '/org/$orgSlug': typeof AppOrganizationSetOrgOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/_no-organization-set/organizations': typeof AppNoOrganizationSetOrganizationsRoute
  '/_app/_organization-set/': typeof AppOrganizationSetIndexRoute
  '/_app/_organization-set/org/$orgSlug': typeof AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren
  '/_app/_organization-set/board/$boardId': typeof AppOrganizationSetBoardBoardIdRoute
  '/_app/_organization-set/org/$orgSlug/team': typeof AppOrganizationSetOrgOrgSlugTeamRoute
  '/_app/_organization-set/org/$orgSlug/': typeof AppOrganizationSetOrgOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/organizations'
    | '/'
    | '/org/$orgSlug'
    | '/board/$boardId'
    | '/org/$orgSlug/team'
    | '/org/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/organizations'
    | '/'
    | '/board/$boardId'
    | '/org/$orgSlug/team'
    | '/org/$orgSlug'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/_no-organization-set/organizations'
    | '/_app/_organization-set/'
    | '/_app/_organization-set/org/$orgSlug'
    | '/_app/_organization-set/board/$boardId'
    | '/_app/_organization-set/org/$orgSlug/team'
    | '/_app/_organization-set/org/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_organization-set/': {
      id: '/_app/_organization-set/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppOrganizationSetIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_no-organization-set/organizations': {
      id: '/_app/_no-organization-set/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppNoOrganizationSetOrganizationsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_organization-set/board/$boardId': {
      id: '/_app/_organization-set/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof AppOrganizationSetBoardBoardIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_organization-set/org/$orgSlug': {
      id: '/_app/_organization-set/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_organization-set/org/$orgSlug/': {
      id: '/_app/_organization-set/org/$orgSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof AppOrganizationSetOrgOrgSlugIndexRouteImport
      parentRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRoute
    }
    '/_app/_organization-set/org/$orgSlug/team': {
      id: '/_app/_organization-set/org/$orgSlug/team'
      path: '/team'
      fullPath: '/org/$orgSlug/team'
      preLoaderRoute: typeof AppOrganizationSetOrgOrgSlugTeamRouteImport
      parentRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRoute
    }
  }
}

interface AppOrganizationSetOrgOrgSlugLayoutRouteChildren {
  AppOrganizationSetOrgOrgSlugTeamRoute: typeof AppOrganizationSetOrgOrgSlugTeamRoute
  AppOrganizationSetOrgOrgSlugIndexRoute: typeof AppOrganizationSetOrgOrgSlugIndexRoute
}

const AppOrganizationSetOrgOrgSlugLayoutRouteChildren: AppOrganizationSetOrgOrgSlugLayoutRouteChildren =
  {
    AppOrganizationSetOrgOrgSlugTeamRoute:
      AppOrganizationSetOrgOrgSlugTeamRoute,
    AppOrganizationSetOrgOrgSlugIndexRoute:
      AppOrganizationSetOrgOrgSlugIndexRoute,
  }

const AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren =
  AppOrganizationSetOrgOrgSlugLayoutRoute._addFileChildren(
    AppOrganizationSetOrgOrgSlugLayoutRouteChildren,
  )

interface AppLayoutRouteChildren {
  AppNoOrganizationSetOrganizationsRoute: typeof AppNoOrganizationSetOrganizationsRoute
  AppOrganizationSetIndexRoute: typeof AppOrganizationSetIndexRoute
  AppOrganizationSetOrgOrgSlugLayoutRoute: typeof AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren
  AppOrganizationSetBoardBoardIdRoute: typeof AppOrganizationSetBoardBoardIdRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppNoOrganizationSetOrganizationsRoute:
    AppNoOrganizationSetOrganizationsRoute,
  AppOrganizationSetIndexRoute: AppOrganizationSetIndexRoute,
  AppOrganizationSetOrgOrgSlugLayoutRoute:
    AppOrganizationSetOrgOrgSlugLayoutRouteWithChildren,
  AppOrganizationSetBoardBoardIdRoute: AppOrganizationSetBoardBoardIdRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
